// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main
{
   public static void main(String args[]) throws Exception
   {
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter book name: ");
       String name = in.readLine();
       System.out.print("Enter book price: ");
       int price = Integer.parseInt(in.readLine());
       System.out.print("Enter book code: ");
       String code = in.readLine();
       System.out.println("OUTPUT:");
       Book p = new Book(name, price);
       System.out.println(p);
       p = new VNBook(name, price, code);
       System.out.println(p);
   }
 }
